sudo: required
script:
    - docker


before_install:
    - docker build -t schemido/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true  schemido/react-test npm test

after_success:
    - docker build -t schemido/multi-client ./client
    - docker build -t schemido/multi-nginx ./nginx
    - docker build -t schemido/multi-server ./server
    - docker build -t schemido/multi-worker ./worker
# log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to docker hub
    - docker push schemido/multi-client
    - docker push schemido/multi-nginx
    - docker push schemido/multi-server
    - docker push schemido/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-708293019169
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
    
    
    
    
    
